spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.sjncjckslkkfqlyyxhpt
spring.datasource.password=Averystrongpassword@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081